version: "3.3"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - baza:/baza/db

  nats:
    image: nats:latest

  device:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      NODEID: "node-device"
      SERVICES: device
    depends_on:
      - nats

  data:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      NODEID: "node-data"
      SERVICES: data

    depends_on:
      - nats
      - mongodb

  analytics:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      NODEID: "node-analytics"
      SERVICES: analytics
    depends_on:
      - nats
      - mongodb

  command:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      NODEID: "node-command"
      SERVICES: command
    depends_on:
      - nats

  gateway:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      NODEID: "node-gateway"
      SERVICES: gateway
    depends_on:
      - nats
    ports:
      - 3000:3000
    
volumes:
  baza: